routes/web.php
<?php
use App\Language;
use Illuminate\Http\Request;
use App\Category;
use App\Item;
use App\Tag;
use App\Comment;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


foreach(Language::all() as $language) {
	Route::group(['prefix' => $language->slug ], function() use ($language){
		Route::get('/', function () use ($language){
		    session(['slug' => $language->slug ]);
		    session(['lang_id'=> $language->id]);
		    session(['dir' => $language->direction]);
		    //return session('lang_id');
		    return view('welcome');
		});

		Route::get('/search', [ 'uses' => 'TagController@search', 'as' => 'search']);
		Route::get('/search/{text}', 'TagController@search2');
		Route::get('/comments_save', [ 'uses' => 'CommentController@store', 'as' => 'comment_save']);
	});
}



Route::get('/backend', function() {
    return view('admin.index');
})->middleware('auth');

Route::resource('/backend/categories', 'CategoryController');

Route::get('/backend/categories/custom_fields/create_custom_field/{id}', [ 'as' => 'categories.create_custom_field' ,function($id) {
	if(!auth()->user()->canDo('add.extrafield')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	return view('custom_fields.create', compact('id'));
}]);

Route::post('/backend/categories/custom_fields', [ 'as' => 'categories.store_custom_field' ,function(Request $request) {
	//return $request;
	DB::table('category_custom_field')->insert([
		'category_id' => $request->input('category_id'),
		'field_key' => $request->input('field_key'),
		'type' => $request->input('type')
	]);

	return redirect()->route('categories.show', $request->input('category_id'));
}]);

Route::delete('/backend/categories/custom_fields/{category_id}/{id}', [ 'as' => 'categories.delete_custom_field' ,function($category_id, $id) {
	if(!auth()->user()->canDo('delete.extrafield')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	
	//$items = Item::where('category_id', $category_id)->get();
	//foreach($items as $item) {
		DB::table('custom_field_item')->where('field_id', '=', $id)->delete();
	//}
	DB::table('category_custom_field')->where('id', '=', $id)->delete();
	return redirect()->route('categories.show', $category_id);
}]);

//Item Extra Field


Route::resource('/backend/items', 'ItemController')->middleware('auth');
Route::resource('comments', 'CommentController');
Route::resource('tags', 'TagController')->middleware('auth');

Route::resource('languages', 'LanguageController')->middleware('auth');

Route::get('/languages/translate/{id}', [ 'as' => 'languages.translate' ,function($id) {
		return view('languages.translate', compact('id'));
	}]);

Route::post('/languages/translate_text', [ 'as' => 'languages.store_text' ,function(Request $request) {
		if(!auth()->user()->canDo('translate.text')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
		DB::table('dictionary')->insert([
			'text' => $request->input('text'),
			'translated_text' => $request->input('translated_text'),
			'language_id' => $request->input('language_id')
		]);

		return redirect()->route('languages.show', $request->input('language_id'));
	}]);

Route::delete('/delete_text/{language_id}/{id}', function($language_id, $id) {
	if(!auth()->user()->canDo('delete.text')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	DB::table('dictionary')->where('id', '=', $id)->delete();

	return redirect()->route('languages.show', $language_id);
});

Route::get('/backend/items/create/{id}', function($id) {
	if(!auth()->user()->canDo('create.item')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

	$languages = Language::all();
    $title = "Create Item";
    $category_id = $id;
    $custom_fields = DB::table('category_custom_field')->where('category_id', $id)->get();
    $tags = Tag::all();

    return view('items.create', compact('languages', 'category_id', 'title', 'custom_fields', 'tags'));
});
Route::resource('/backend/menus', 'MenuController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/backend/users', 'UserController')->middleware('auth');
Route::resource('/backend/roles', 'RoleController')->middleware('auth');
Route::post('/backend/roles/addpermissions', [ 'as' => 'roles.addpermissions', 'uses' => 'RoleController@addPermissions'])->middleware('auth');

app/Language.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class Language extends Model
{
    public function categories()
    {
    	return $this->belongsToMany('App\Category');
    }

    public static function translate($text)
    {
        

    	$collection = DB::table('dictionary')->where('text', '=', $text)->where('language_id', '=', session('lang_id'))->get();
    	if(count($collection)) {
    		return $collection[0]->translated_text;
    	} else {
    		return $text;
    	}
    }

    public static function paddedDesc($text)
    {
        if(strlen($text) == 50) {
            return $text;
        } elseif(strlen($text) < 50) {
            $test = '';
            for($i=0; $i < (50 - strlen($text)); $i++) {
                $test = $test.'&nbsp;';
            }
            return $text.'<p>'.$test.'</p>';
        } else {
            return '<p>'.substr($text, 0, 50).'</p>';
        }
    }
}

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Language;
use DB;

class LanguageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $languages = Language::all();
        return view('languages.index', compact('languages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!auth()->user()->canDo('add.language')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

        $language = new Language;
        $language->name = $request->input('name');
        $language->direction = $request->input('dir');
        $language->slug = $request->input('slug');
        $language->save();

        return redirect()->route('languages.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(!auth()->user()->canDo('show.category')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

        $language = Language::find($id);
        $dictionaryTexts = DB::table('dictionary')->where('language_id', '=', $id)->get();

        return view('languages.show', compact('language', 'dictionaryTexts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!auth()->user()->canDo('delete.language')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

        $language = Language::find($id);
        DB::table('category_language')->where('language_id', '=', $id)->delete();
        DB::table('item_language')->where('language_id', '=', $id)->delete();
        DB::table('language_menu')->where('language_id', '=', $id)->delete();
        DB::table('dictionary')->where('language_id', '=', $id)->delete();
        $language->delete();

        return redirect()->route('languages.index');
    }
}

resources/views/languages/index.blade.php
@extends('layouts.main_admin')

@section('title', 'Languages')

@section('content')
	<div class="row" style="padding-top: 50px;">
		<div class="col s8">
			
		<table class="bordered highlight">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				
					@foreach($languages as $language)
					<tr>
						<td>{{ $language->id }}</td>
						<td><a href="{{ route('languages.show', $language->id) }}">{{ $language->name }}</a></td>
						
						<td class="right"> 
						@if($language->slug != 'en')
						<form action="{{ route('languages.destroy', $language->id) }}" method="POST">
							<input type="hidden" name="_method" value="DELETE">
    						<input type="hidden" name="_token" value="{{ csrf_token() }}">
							<button class="waves-effect waves-light btn red tiny" type="submit">Delete</button>	
						</form>
						@endif
						</td>
					</tr>
					@endforeach
				
			</tbody>
		</table>	
		</div>
		<div class="col s4">
			<div class="card">
				<h5 class="center" style="padding-top: 20px;">Create New Language</h5>
				<form action="{{ route('languages.store') }}" method="POST">
					{{ csrf_field() }}
					<div class="card-content">

						<div class="input-field">
							<input type="text" id="name" name="name" class="validate">
							<label for="name">Name</label>					
						</div>
						
						<div class="input-field">
							<input type="text" id="dir" name="dir" class="validate">
							<label for="dir">Direction: (ltr, rtl)</label>					
						</div>

						<div class="input-field">
							<input type="text" id="slug" name="slug" class="validate">
							<label for="slug">Slug</label>					
						</div>
					</div>
					<div class="card-action">
						<button class="waves-effect waves-light btn" type="submit" href="#">
						Create
					</button>							
					</div>
				</form>

			</div>
		</div>
			
	</div>
	
@endsection

resources/views/languages/show.blade.php
@extends('layouts.main_admin')


@section('content')
	<div class="row">
		
		<div class="col s8">
			<ul class="collapsible" data-collapsible="accordion">
				<li>
					<div class="collapsible-header active"><strong>Name</strong></div>
					<div class="collapsible-body">{{ $language->name }}</div>
				</li>

				<li>
					<div class="collapsible-header"><strong>Direction</strong></div>
					<div class="collapsible-body">{{ $language->dir}}</div>
				</li>

				<li>
					<div class="collapsible-header"><strong>Slug</strong></div>
					<div class="collapsible-body">{!! $language->slug !!}</div>
				</li>
			</ul>
		</div>
	
	<div class="col s8" style="padding-top: 50px;">
		<a class="waves-effect waves-light btn" href="{{ route('languages.translate', $language->id) }}">Translate Text</a>
		<table class="bordered highlight">
			<thead>
				<tr>
					<th>#</th>
					<th>Text</th>
					<th>Translated Text</th>
					<th></th>
					
				</tr>
			</thead>

			<tbody>
					@foreach($dictionaryTexts as $text)
					<tr>
						<td>{{ $text->id }}</td>
						<td>{{ $text->text }}</td>
						<td>{{ $text->translated_text }}</td>
						
						<td class="right">
						<form action="{{ url('/delete_text/'.$language->id.'/'.$text->id) }}" method="POST">
							<input type="hidden" name="_method" value="DELETE">
    						<input type="hidden" name="_token" value="{{ csrf_token() }}">
							<button class="waves-effect waves-light btn red tiny" type="submit">Delete</button>	
						</form>
						</td>
					</tr>
					@endforeach
				
			</tbody>
		</table>	
	</div>
@endsection


@section('script')
	<script type="text/javascript">
		$(document).ready(function(){
    		$('.collapsible').collapsible();
  		});	
	</script>
@endsection

resources/views/languages/translate.blade.php
@extends('layouts.main_admin')


@section('content')
	<div class="row">
		<h4>Translate Text</h4>
		<form action="{{ route('languages.store_text') }}" method="POST">
			{{ csrf_field() }}
			<div class="col s4">
				<div class="input-field" style="padding-top: 20px;">
					<input type="text" id="text" name="text" class="validate">
					<label for="text">Text</label>
				</div>

				<div class="input-field" style="padding-top: 20px;">
					<input type="text" id="translated_text" name="translated_text" class="validate">
					<label for="translated_text">Translated Text</label>
				</div>
				
				<input type="hidden" name="language_id" value="{{ $id }}">
				<button type="submit" class="btn btn-info">Submit</button>
				
			</div>
		</form>
	</div>

@endsection