routes/web.php
<?php
use App\Language;
use Illuminate\Http\Request;
use App\Category;
use App\Item;
use App\Tag;
use App\Comment;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


foreach(Language::all() as $language) {
	Route::group(['prefix' => $language->slug ], function() use ($language){
		Route::get('/', function () use ($language){
		    session(['slug' => $language->slug ]);
		    session(['lang_id'=> $language->id]);
		    session(['dir' => $language->direction]);
		    //return session('lang_id');
		    return view('welcome');
		});

		Route::get('/search', [ 'uses' => 'TagController@search', 'as' => 'search']);
		Route::get('/search/{text}', 'TagController@search2');
		Route::get('/comments_save', [ 'uses' => 'CommentController@store', 'as' => 'comment_save']);
	});
}



Route::get('/backend', function() {
    return view('admin.index');
})->middleware('auth');

Route::resource('/backend/categories', 'CategoryController');

Route::get('/backend/categories/custom_fields/create_custom_field/{id}', [ 'as' => 'categories.create_custom_field' ,function($id) {
	if(!auth()->user()->canDo('add.extrafield')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	return view('custom_fields.create', compact('id'));
}]);

Route::post('/backend/categories/custom_fields', [ 'as' => 'categories.store_custom_field' ,function(Request $request) {
	//return $request;
	DB::table('category_custom_field')->insert([
		'category_id' => $request->input('category_id'),
		'field_key' => $request->input('field_key'),
		'type' => $request->input('type')
	]);

	return redirect()->route('categories.show', $request->input('category_id'));
}]);

Route::delete('/backend/categories/custom_fields/{category_id}/{id}', [ 'as' => 'categories.delete_custom_field' ,function($category_id, $id) {
	if(!auth()->user()->canDo('delete.extrafield')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	
	//$items = Item::where('category_id', $category_id)->get();
	//foreach($items as $item) {
		DB::table('custom_field_item')->where('field_id', '=', $id)->delete();
	//}
	DB::table('category_custom_field')->where('id', '=', $id)->delete();
	return redirect()->route('categories.show', $category_id);
}]);

//Item Extra Field


Route::resource('/backend/items', 'ItemController')->middleware('auth');
Route::resource('comments', 'CommentController');
Route::resource('tags', 'TagController')->middleware('auth');

Route::resource('languages', 'LanguageController')->middleware('auth');

Route::get('/languages/translate/{id}', [ 'as' => 'languages.translate' ,function($id) {
		return view('languages.translate', compact('id'));
	}]);

Route::post('/languages/translate_text', [ 'as' => 'languages.store_text' ,function(Request $request) {
		if(!auth()->user()->canDo('translate.text')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
		DB::table('dictionary')->insert([
			'text' => $request->input('text'),
			'translated_text' => $request->input('translated_text'),
			'language_id' => $request->input('language_id')
		]);

		return redirect()->route('languages.show', $request->input('language_id'));
	}]);

Route::delete('/delete_text/{language_id}/{id}', function($language_id, $id) {
	if(!auth()->user()->canDo('delete.text')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	DB::table('dictionary')->where('id', '=', $id)->delete();

	return redirect()->route('languages.show', $language_id);
});

Route::get('/backend/items/create/{id}', function($id) {
	if(!auth()->user()->canDo('create.item')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

	$languages = Language::all();
    $title = "Create Item";
    $category_id = $id;
    $custom_fields = DB::table('category_custom_field')->where('category_id', $id)->get();
    $tags = Tag::all();

    return view('items.create', compact('languages', 'category_id', 'title', 'custom_fields', 'tags'));
});
Route::resource('/backend/menus', 'MenuController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/backend/users', 'UserController')->middleware('auth');
Route::resource('/backend/roles', 'RoleController')->middleware('auth');
Route::post('/backend/roles/addpermissions', [ 'as' => 'roles.addpermissions', 'uses' => 'RoleController@addPermissions'])->middleware('auth');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\item;
use Baum\Node;

class Category extends Node
{
	protected $guarded = [];
    public function languages()
    {
    	return $this->belongsToMany('App\Language')->withPivot('category_id', 'language_id', 'title', 'desc');
    }

    public function items()
    {
        return $this->hasMany('App\Item');
    }

    public static function getCategoryType($id)
    {
    	$type= "";

        $categories = static::where('parent', $id)->get();

        if(count($categories) == 0) {
            $items = Item::where('category_id', $id)->get();
            if(count($items) == 1) {
                $type = "item_per_page";
            } else {
                $type = "list_of_items";
            }
        } else {
            $type= "list_of_categories";
        }

        return $type;
    }

    public function paddedTitle($id = 1)
    {
        return str_repeat('&nbsp;', $this->depth*4).$this->languages()->first()->pivot->title;
        $title =  Category::whereHas('languages', function($query) use ($id) {
            return $query->where('language_id', $id);
        })->get();

        //return $title;
        return str_repeat('&nbsp;', $title[0]->title);
    }

    public function updateOrder($parent_id)
    {
        $Category = $this->findOrFail($parent_id);
        $this->makeChildOf($Category);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Item;
use App\Language;
use DB;
use Session;
use App\Menu;
use Baum\MoveNotPossibleException;
use App\Comment;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //return Category::with('languages')->get();

        $categories = Category::all();
        return view('categories.index')->withCategories($categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!auth()->user()->canDo('create.category')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

        $title = 'Create New Category';
        $categories = Category::all();
        $languages = Language::all();
        return view('categories.create', compact('category', 'title', 'categories', 'languages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        //return $request;
        $this->validate($request, [
            'slug' => 'unique:categories'
        ]);

        if($request->has('parent_id')) {
            $menu = Menu::where('category_id', $request->input('parent_id'))->first();
            if($menu) {
                if($menu->type != 'list_of_categories') {
                    return redirect()->route('categories.index')->withErrors([
                        'error' => 'You Can not add categories to this category'
                    ]);
                }
            } else {
                $items = Item::where('category_id', $request->input('parent_id'))->first();
                if($items) {
                    return redirect()->route('categories.index')->withErrors([
                        'error' => 'You can not add Catgeory to this Category Parent.'
                    ]);
                }
            }
        }

        $category = new Category;

        foreach(Language::all() as $language) {

            if($language->slug == "en") {
                $url = '';
                $category->url = $this->setUrl($request->input('parent_id'), $url).strtolower($request->input('slug'));

                if($request->hasFile('image')) {
                    $image = $request->file('image');
                    $image_name = time()."-".$image->getClientOriginalExtension();
                    $image->move('images', $image_name);
                    $category->image = $image_name;
                }

                $category->created_by = auth()->user()->id;
                $category->updated_by = auth()->user()->id;
            }

        }

        $category->slug = $request->input('slug');
        $category->save();

        $this->updateCategoryOrder($category, $request);            
        $category->save();

        foreach (Language::all() as $language) {
            if($request->input('title_'.$language->slug) && $request->input('title_'.$language->slug)) {
                $category->languages()->attach($language->id, ['title' => $request->input('title_'.$language->slug), 'desc' => $request->input('desc_'.$language->slug)]);
            }    
        }
        
        Session::flash('success', 'This Category was successfully created.');

        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(!auth()->user()->canDo('show.category')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
        $category = Category::find($id);

        //return $category->languages()->first()->pivot->title;
        $items = Item::where('category_id', $category->id)->get();
        $custom_fields = DB::table('category_custom_field')->where('category_id', '=', $id)->get();
        return view('categories.show', compact('category', 'items', 'custom_fields'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!auth()->user()->canDo('edit.category')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

        $category = Category::find($id);
        //return $category;
        $categories = Category::all();
        $title = 'Edit Category';
        $languages = Language::all();
        return view('categories.edit', compact('category', 'title', 'categories', 'languages'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //return $request;
        $category = Category::find($id);
        if($request->input('slug') != $category->slug) {
            $this->validate($request, [
                'slug' => 'unique:categories'
            ]);
        }
        
        $parent_id = $category->parent_id;

        foreach(Language::all() as $language) {
            if($language->slug == 'en') {
                $category->fill($request->only('parent_id'));  
                
                $url = '';
        
                if($request->has('parent_id')) {
                    $category->url = 
                    $this->setUrl($request->input('parent_id'), $url).strtolower($request->input('slug'));            
                }

                if($request->has('title_en') && !$request->has('parent_id')) {
                    $category->url = 
                    $this->setUrl($parent_id, $url).strtolower($request->input('slug'));            
                }

                

                if($request->hasFile('image')) {
                    $image = $request->file('image');
                    $image_name = time()."-".$image->getClientOriginalExtension();
                    $image->move('images', $image_name);
                    $category->image = $image_name;
                }


            }

        }

        $category->updated_by = auth()->user()->id;

        if($response = $this->updateCategoryOrder($category, $request)) {
            return $response;
        }    
        $category->slug = $request->input('slug');
        $category->save();

        $data = [];
        foreach(Language::all() as $language) {
            $data[$language->id] = [ 'title' => $request->input('title_'.$language->slug),
            'desc' => $request->input('desc_'.$language->slug)];
           
        }

         $category->languages()->sync($data);
        
        Session::flash('success', 'This Category was successfully updated.');
        return redirect()->route('categories.show', $category->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!auth()->user()->canDo('delete.category')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }


        $menu = Menu::where('category_id', $id)->first();
        if($menu) {
            $menu->languages()->detach();
            $menu->delete();
        }

        $items = Item::where('category_id', $id)->get();

        foreach ($items as $item) {
            $comments = Comment::where('item_id', $item->id)->get();
            foreach($comments as $comment) {
                $comment->delete();
            }
            $item->tags()->detach();
            DB::table('custom_field_item')->where('item_id', '=', $item->id)->delete();
            $item->languages()->detach();
            $item->delete();    
        }
        
        DB::table('category_custom_field')->where('category_id', '=', $id)->delete();
        
        $category = Category::find($id);
        foreach($category->children as $child) {
            $child->makeRoot();
            $url = '';
            $this->setChildUrl($child, $url, $category->parent_id).strtolower($child->slug);
            $child->save();
        }

        $category->languages()->detach();
        $category->delete();
        
        Session::flash('success', 'This Category was successfully deleted.');
        return redirect()->route('categories.index');
    }


    public function setUrl($id, $url)
    {
        $parent = Category::where('id', $id)->get();
        
        //return $parent;
        if(!count($parent)) {
            return '';
        }

        if($parent[0]->url) {
            return $parent[0]->url.'/';
        }

        if($url) {
            $url = $url.'/'.strtolower($parent[0]->slug);
        } else {
            $url = strtolower($parent[0]->languages()->slug).'/';
        }
        
        $this->setUrl($parent[0]->parent_id, $url);

        return $url;
    }

    public function updateCategoryOrder(Category $category, Request $request)
    {
        if($request->has('parent_id')) {
            try {
                $category->updateOrder($request->input('parent_id'));
            } catch (MoveNotPossibleException $e) {
                return redirect()->route('categories.index')->withInput()->withErrors([

resources/views/categories/create.blade.php
@extends('layouts.main_admin')

@section('title', 'Categories')

@section('content')

	<div class="container">
		<h5>{{ $title }}</h5>

		<form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div class="col s12">
		      <ul class="tabs">
		      	@foreach($languages as $language)
		        	<li class="tab col s3">
		        		<a href="#{{ $language->slug }}">{{ $language->name }}</a>
		        	</li>
		        @endforeach
		      </ul>
		  	</div>
		     @foreach($languages as $language)
			<div class="col s12" id="{{ $language->slug }}">
				<div class="input-field" style="padding-top: 20px;">
					<input type="text" id="title_{{ $language->slug }}" name="title_{{ $language->slug }}" class="validate" value="{{ $category->title or old('title') }}">
					<label for="title">Title</label>
															
				</div>

				@if($language->slug == "en")
					<div class="input-field" style="padding-top: 20px;">
						<input type="text" id="slug" name="slug" class="validate">
						<label for="slug">Slug</label>
																
					</div>
				

				<div class="input-field" style="padding-top: 20px;">
				    <select class="icons" name="parent_id">
				      <option value="" disabled selected>Choose your option</option>
				      @foreach($categories as $c)
						<option value="{{ $c->id }}" data-icon="/images/{{ $c->image }}" class="left circle">{{ $c->paddedTitle($c->id) }}</option>
				      @endforeach
				      
				    </select>
				    <label for="parent_id">Parent</label>
				</div>


				<div class="file-field input-field"  style="padding-top: 20px;">
			      <div class="btn">
			        <span>Image</span>
			        <input type="file" type="text" name="image" >
			      </div>
			      <div class="file-path-wrapper">
			        <input class="file-path validate" value="{{ $category->image or old('image') }}">
			      </div>
    			</div>
				@endif
    			<div style="padding-top: 20px;">
					<label for="desc">Description</label>
					<textarea name="desc_{{ $language->slug }}" id="desc_{{ $language->slug }}">{{ $category->desc or old('desc') }}</textarea>
    			</div>

				
			</div>
			@endforeach
			<div style="padding-top: 20px;">
					<button type="submit" class="btn waves-effect waves-light large">Submit</button>	
			</div>
		</form>
	</div>

@endsection

@section('script')
	<script type="text/javascript">
		$(document).ready(function() {
			$('select').material_select();
		});	
	</script>

	<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
    	@foreach($languages as $language)
        	CKEDITOR.replace('desc_{{ $language->slug }}');
        @endforeach
    </script>

@endsection

resources/views/categories/edit.blade.php
@extends('layouts.main_admin')

@section('title', 'Categories')

@section('content')

	<div class="container">
		<h5>{{ $title }}</h5>

		<form action="{{ route('categories.update', $category->id) }}" method="POST" enctype="multipart/form-data">
			{{ csrf_field() }}
			{{ method_field('PUT') }}
			<ul class="tabs">
		      	@foreach($languages as $language)
		        	<li class="tab col s3">
		        		<a href="#{{ $language->slug }}">{{ $language->name }}</a>
		        	</li>
		        @endforeach
		      </ul>
		     @foreach($languages as $language)
			<div class="col s12" id="{{ $language->slug }}">
				<div class="input-field" style="padding-top: 20px;">
					<input type="text" id="title_{{ $language->slug }}" name="title_{{ $language->slug }}" class="validate" value="{{ $category->languages->find($language->id)->pivot->title or old('title') }}">
					<label for="title">Title</label>
															
				</div>

				@if($language->slug == "en")
					<div class="input-field" style="padding-top: 20px;">
						<input type="text" id="slug" name="slug" class="validate" value="{{ $category->slug or old('title') }}">
						<label for="slug">Slug</label>
																
					</div>
				
				
				<div class="input-field" style="padding-top: 20px;">
				    <select class="icons" name="parent_id">
				      <option disabled selected>Choose your option</option>
				      @foreach($categories as $c)
						<option value="{{ $c->id }}" data-icon="/images/{{ $c->image }}" class="left circle">{{ $c->paddedTitle() }}</option>
				      @endforeach
				      
				    </select>
				    <label for="parent_id">Parent</label>
				</div>


				<div class="file-field input-field"  style="padding-top: 20px;">
			      <div class="btn">
			        <span>Image</span>
			        <input type="file" type="text" name="image" >
			      </div>
			      <div class="file-path-wrapper">
			        <input class="file-path validate">
			        <img src="/images/{{ $category->image }}" height="256" width="256">
			      </div>
    			</div>
				@endif
    			<div style="padding-top: 20px;">
					<label for="desc">Description</label>
					<textarea name="desc_{{ $language->slug }}"" id="desc_{{ $language->slug }}">{{ $category->languages->find($language->id)->pivot->desc or old('desc') }}</textarea>
    			</div>
			</div>
			@endforeach

			<div style="padding-top: 20px;">
					<button type="submit" class="btn waves-effect waves-light large">Submit</button>	
				</div>
		</form>
	</div>

@endsection

@section('script')
	<script type="text/javascript">
		$(document).ready(function() {
			$('select').material_select();
		});	
	</script>

	<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
    	@foreach($languages as $language)
        	CKEDITOR.replace('desc_{{ $language->slug }}');
        @endforeach
    </script>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.main_admin')

@section('title', 'Categories')


@section('content')
	<div class="row" style="padding-top: 50px;">
		<div class="col s12">
			<a class="waves-effect waves-light btn" href="{{ route('categories.create') }}">Create New Category</a>
		<table class="bordered highlight">
			<thead>
				<tr>
					<th>#</th>
					<th>Title</th>
					
					<th>Url</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				
					@foreach($categories as $category)
					<tr>
						<td>{{ $category->id }}</td>
						<td><a href="{{ route('categories.show', $category->id) }}"	class="waves-effect waves-light">{{ $category->paddedTitle() }}</a></td>
						
						<td><a href="{{ url($category->url) }}">{{ $category->url }}</a></td>
						<td class="right"> 
						<form action="{{ route('categories.destroy', $category->id) }}" method="POST">
							<input type="hidden" name="_method" value="DELETE">
    						<input type="hidden" name="_token" value="{{ csrf_token() }}">
							<button class="waves-effect waves-light btn red tiny" type="submit">Delete</button>	
						</form>
						</td>
					</tr>
					@endforeach
				
			</tbody>
		</table>	
		</div>
			
	</div>
	
@endsection

resources/views/categories/show.blade.php
@extends('layouts.main_admin')


@section('content')
	<div class="row">
		
		
		<div class="col s8">
			@foreach(App\Language::all() as $language)
			@if($category->languages->find($language->id))
			<ul class="collapsible" data-collapsible="accordion">
				
				<li>
					<div class="collapsible-header active"><strong>Title</strong></div>
					<div class="collapsible-body">{{ $category->languages->find($language->id)->pivot->title }}</div>
				</li>

				<li>
					<div class="collapsible-header"><strong>Image</strong></div>
					<div class="collapsible-body"><img height="256" width="256" src="/images/{{$category->image}}"></div>
				</li>

				<li>
					<div class="collapsible-header"><strong>Description</strong></div>
					<div class="collapsible-body">{!! $category->languages->find($language->id)->pivot->desc !!}</div>
				</li>
				
			</ul>
			@endif
			@endforeach
		</div>
		
	

	
	<div class="col s4">
		<div class="card">
            <div class="card-content">

              <p><strong>Created At:</strong> <h6>{{$category->created_at }}</h6></p>
              <p><strong>Updated At:</strong> <h6>{{$category->updated_at }}</h6></p>
              <p><strong>Created By:</strong> <h6>{{$category->created_by }}</h6></p>
              <p><strong>Updated By:</strong> <h6>{{$category->created_by }}</h6></p>             

            </div>
            <div class="card-action">
              <div class="left"><a href="{{ route('categories.edit', $category->id) }}" class="waves-effect waves-light btn large">&nbsp; Edit &nbsp;</a></div>
              <div class="right">
              	<form action="{{ route('categories.destroy', $category->id) }}" method="POST">
					<input type="hidden" name="_method" value="DELETE">
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					<button class="waves-effect waves-light btn red" type="submit">Delete</button>	
				</form>
              </div>

              <div style="padding-top:50px;"><a style="padding:0 80px;" href="{{ route('categories.index') }}" class="waves-effect waves-light btn blue">Show All Items</a></div>
              <div>
            </div>
          </div>
		</div>
	</div>
</div>
	<div class="row">
		<div class="col s8">
			<a class="waves-effect waves-light btn" href="{{ url('/') }}/backend/items/create/{{ $category->id }}">Create New Item</a>
		<table class="bordered highlight">
			<thead>
				<tr>
					<th>#</th>
					<th>Title</th>
					<th></th>
					
				</tr>
			</thead>

			<tbody>
					@foreach($items as $item)
					<tr>
						<td>{{ $item->id }}</td>
						<td><a href="{{ route('items.show', $item->id) }}">{{ $item->languages()->first()->pivot->title }}</a></td>
						
						<td class="right">
						<form action="{{ route('items.destroy', $item->id) }}" method="POST">
							<input type="hidden" name="_method" value="DELETE">
    						<input type="hidden" name="_token" value="{{ csrf_token() }}">
							<button class="waves-effect waves-light btn red tiny" type="submit">Delete</button>	
						</form>
						</td>
					</tr>
					@endforeach
				
			</tbody>
		</table>	
		</div>

		
			<div class="col s4 offset-s8">
				<div class="card">
					<div class="center" style="padding-top: 20px;">
						<i>Extra Catgeory Fields</i>
					</div>
		            <div class="card-content">
					
						<table class="bordered">
							<thead>
								<tr>
									<th>key</th>
									<th>Type</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach($custom_fields as $custom_field)
								<tr>
									<td>{{ $custom_field->field_key }}</td>
									<td>{{ $custom_field->type }}</td>
									<td>
										<form action="{{ route('categories.delete_custom_field', [ 'category_id' => $category->id, 'id' => $custom_field->id]) }}" 
											method="POST">
											<input type="hidden" name="_method" value="DELETE">
											<input type="hidden" name="_token" value="{{ csrf_token() }}">
											<button class="waves-effect waves-light btn red tiny" type="submit" href="#">Delete</button>
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
		              
		            </div>
		            <div class="card-action">
		              <div class="center"><a style="padding:0 100px;" href="{{ route('categories.create_custom_field', $category->id) }}" class="waves-effect waves-light btn ">Create</a></div>
		              <div>
		            </div>
		          </div>
				</div>
			</div>
			
			
	</div>
	
	
@endsection


@section('script')
	<script type="text/javascript">

		$(document).ready(function(){
    		$('.collapsible').collapsible();
  		});	
	</script>
@endsection