routes/web.php
<?php
use App\Language;
use Illuminate\Http\Request;
use App\Category;
use App\Item;
use App\Tag;
use App\Comment;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


foreach(Language::all() as $language) {
	Route::group(['prefix' => $language->slug ], function() use ($language){
		Route::get('/', function () use ($language){
		    session(['slug' => $language->slug ]);
		    session(['lang_id'=> $language->id]);
		    session(['dir' => $language->direction]);
		    //return session('lang_id');
		    return view('welcome');
		});

		Route::get('/search', [ 'uses' => 'TagController@search', 'as' => 'search']);
		Route::get('/search/{text}', 'TagController@search2');
		Route::get('/comments_save', [ 'uses' => 'CommentController@store', 'as' => 'comment_save']);
	});
}



Route::get('/backend', function() {
    return view('admin.index');
})->middleware('auth');

Route::resource('/backend/categories', 'CategoryController');

Route::get('/backend/categories/custom_fields/create_custom_field/{id}', [ 'as' => 'categories.create_custom_field' ,function($id) {
	if(!auth()->user()->canDo('add.extrafield')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	return view('custom_fields.create', compact('id'));
}]);

Route::post('/backend/categories/custom_fields', [ 'as' => 'categories.store_custom_field' ,function(Request $request) {
	//return $request;
	DB::table('category_custom_field')->insert([
		'category_id' => $request->input('category_id'),
		'field_key' => $request->input('field_key'),
		'type' => $request->input('type')
	]);

	return redirect()->route('categories.show', $request->input('category_id'));
}]);

Route::delete('/backend/categories/custom_fields/{category_id}/{id}', [ 'as' => 'categories.delete_custom_field' ,function($category_id, $id) {
	if(!auth()->user()->canDo('delete.extrafield')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	
	//$items = Item::where('category_id', $category_id)->get();
	//foreach($items as $item) {
		DB::table('custom_field_item')->where('field_id', '=', $id)->delete();
	//}
	DB::table('category_custom_field')->where('id', '=', $id)->delete();
	return redirect()->route('categories.show', $category_id);
}]);

//Item Extra Field


Route::resource('/backend/items', 'ItemController')->middleware('auth');
Route::resource('comments', 'CommentController');
Route::resource('tags', 'TagController')->middleware('auth');

Route::resource('languages', 'LanguageController')->middleware('auth');

Route::get('/languages/translate/{id}', [ 'as' => 'languages.translate' ,function($id) {
		return view('languages.translate', compact('id'));
	}]);

Route::post('/languages/translate_text', [ 'as' => 'languages.store_text' ,function(Request $request) {
		if(!auth()->user()->canDo('translate.text')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
		DB::table('dictionary')->insert([
			'text' => $request->input('text'),
			'translated_text' => $request->input('translated_text'),
			'language_id' => $request->input('language_id')
		]);

		return redirect()->route('languages.show', $request->input('language_id'));
	}]);

Route::delete('/delete_text/{language_id}/{id}', function($language_id, $id) {
	if(!auth()->user()->canDo('delete.text')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	DB::table('dictionary')->where('id', '=', $id)->delete();

	return redirect()->route('languages.show', $language_id);
});

Route::get('/backend/items/create/{id}', function($id) {
	if(!auth()->user()->canDo('create.item')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

	$languages = Language::all();
    $title = "Create Item";
    $category_id = $id;
    $custom_fields = DB::table('category_custom_field')->where('category_id', $id)->get();
    $tags = Tag::all();

    return view('items.create', compact('languages', 'category_id', 'title', 'custom_fields', 'tags'));
});
Route::resource('/backend/menus', 'MenuController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/backend/users', 'UserController')->middleware('auth');
Route::resource('/backend/roles', 'RoleController')->middleware('auth');
Route::post('/backend/roles/addpermissions', [ 'as' => 'roles.addpermissions', 'uses' => 'RoleController@addPermissions'])->middleware('auth');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
	protected $guarded= [];

    public function languages()
    {
    	return $this->belongsToMany('App\Language')->withPivot('item_id', 'language_id', 'title', 'info', 'desc');
    }

    public function tags()
    {
    	return $this->belongsToMany('App\Tag', 'item_tag', 'item_id', 'tag_id');
    }

    public function categories()
    {
    	return $this->belongsTo('App\Category', 'category_id');
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use Illuminate\Http\Request;
use App\Language;
use App\Category;
use DB;
use App\Menu;
use App\Tag;
use App\Comment;

class ItemController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::all();
        return view('items.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //return $category;
        $languages = Language::all();
        $title = "Create Item";

        return view('items.create', compact('languages', 'category', 'title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return $request;
        foreach(Language::all() as $language) {
            $this->validate($request, [
            'title_'.$language->slug => 'required',
            'desc_'.$language->slug => 'required',
            'info_'.$language->slug => 'required'
        ]);
        }

        $menu = Menu::where('category_id', $request->input('category_id'))->first();
        if($menu) {
            if($menu->type == 'list_of_categories') {
                return redirect()->route('categories.index')->withErrors([
                    'error' => 'You Can not add items to this category'
                ]);
            } elseif($menu->type == 'item_per_page') {
                $items = Item::where('category_id', $request->input('category_id'))->get();
                if(count($items) >= 1) {
                   return redirect()->route('categories.index')->withErrors([
                    'error' => 'You Can not add items to this category'
                ]); 
                }
            }
        }

        $parent = Category::where('id', $request->input('category_id'))->first();
        if(count($parent->children)) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You can not add item to this Category Parent.'
            ]);
        }
        

        $item = new Item;
        
        $item->category_id = $request->input('category_id');
        if($request->hasFile('image')) {
            $image = $request->file('image');
            $image_name = time()."-".$image->getClientOriginalExtension();
            $image->move('images', $image_name);
            
            $item->image = $image_name;
        }

        $item->created_by = auth()->user()->id;
        $item->updated_by = auth()->user()->id;

        $item->save();
        foreach(Language::all() as $language) {
            $item->languages()->attach($language->id, ['title' => $request->input('title_'.$language->slug), 'desc' => $request->input('desc_'.$language->slug), 'info' => $request->input('info_'.$language->slug)]);
            $item->tags()->sync($request->input('tags_'.$language->slug), false);
        }
        
        if($request->input('length') > 0) {
            for($i =0; $i < $request->input('length'); $i++) {
                if($request->has('custom_field_value'.$i)) {
                    DB::table('custom_field_item')->insert([
                        'item_id' => $item->id,
                        'value' => $request->input('custom_field_value'.$i),
                        'field_id' =>  $request->input('field_id'.$i)
                    ]);
                } elseif ($request->hasFile('custom_field_value_file'.$i)) {
                    $file = $request->file('custom_field_value_file'.$i);
                    $file_name = time()."-".$file->getClientOriginalExtension();
                    $file->move('files', $file_name);
                    DB::table('custom_field_item')->insert([
                        'item_id' => $item->id,
                        'value' => $file_name,
                        'field_id' =>  $request->input('field_id'.$i)
                    ]);
                    
                }
            }
        }
        
        return redirect()->route('categories.show', $item->category_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        if(!auth()->user()->canDo('show.items')) {
            return redirect()->route('items.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

        $custom_fields = DB::table('category_custom_field')
                        ->select('category_custom_field.id', 'category_custom_field.field_key', 'category_custom_field.type', 'custom_field_item.value')
                        ->leftjoin('custom_field_item', 'category_custom_field.id', '=', 'custom_field_item.field_id')
                        ->where(['category_custom_field.category_id' => $item->category_id, 'custom_field_item.item_id' => $item->id])
                        ->get();
        return view('items.show', compact('item', 'custom_fields'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        if(!auth()->user()->canDo('edit.item')) {
            return redirect()->route('items.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

        $languages = Language::all();
        $categories = Category::all();
        $category_id = $item->category_id;
        
        /*
        $custom_fields = DB::table('category_custom_field')
                    ->select('category_custom_field.id', 'category_custom_field.field_key', 'category_custom_field.type', 'custom_field_item.value')
                    ->leftjoin('custom_field_item', 'category_custom_field.id', '=', 'custom_field_item.field_id')
                    ->leftjoin('custom_field_item', 'category_custom_field.id', '!=', 'custom_field_item.field_id')
                    ->where(['category_custom_field.category_id' => $item->category_id])

                    ->get();
                    */
        $exist = DB::table('custom_field_item')->where('item_id', '=', $item->id)->get();
        //return $exist;
        $custom_fields = DB::table('category_custom_field')
                            ->leftjoin('custom_field_item', function($join) use($exist, $item){
                                $join->on('category_custom_field.id', '=', 'custom_field_item.field_id')
                                ->where('custom_field_item.item_id', '=', count($exist) ? $item->id : null);
                            })
                            ->select('category_custom_field.id', 'category_custom_field.field_key', 'category_custom_field.type', 'custom_field_item.value')
                            ->get();
                            
        $title = "Edit Item";
        //return $custom_fields;
        $tags = Tag::all();

        return view('items.edit', compact('languages', 'categories', 'title', 'item', 'category_id', 'custom_fields', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        //return $request;

        $item->fill($request->only(['category_id']));
        
        if($request->hasFile('image')) {
            $image = $request->file('image');
            $image_name = time()."-".$image->getClientOriginalExtension();
            $image->move('images', $image_name);
            
            $item->image = $image_name;
        }

        $item->updated_by = auth()->user()->id;
        $item->save();

        $data = [];
        foreach(Language::all() as $language) {
            $data[$language->id] = ['title' => $request->input('title_'.$language->slug), 'desc' => $request->input('desc_'.$language->slug), 'info' => $request->input('info_'.$language->slug)];
        }

        $item->languages()->sync($data);

        if($request->input('length') > 0) {
            for($i =0; $i < $request->input('length'); $i++) {
                if($request->has('custom_field_value'.$i)) {
                    $query = DB::table('custom_field_item')->where('field_id', '=', $request->input('field_id'.$i))->get();
                    if(count($query)) {
                        DB::table('custom_field_item')->where('item_id', '=', $item->id)
                        ->where('field_id', '=', $request->input('field_id'.$i))->update([
                            'value' => $request->input('custom_field_value'.$i),
                        ]);
                    } else {
                        DB::table('custom_field_item')->insert([
                        'item_id' => $item->id,
                        'value' => $request->input('custom_field_value'.$i),
                        'field_id' =>  $request->input('field_id'.$i)
                    ]);
                    }
                    
                } elseif ($request->hasFile('custom_field_value_file'.$i)) {
                    $query = DB::table('custom_field_item')->where('field_id', '=', $request->input('field_id'.$i))->get();
                    if(count($query)) {
                        $file = $request->file('custom_field_value_file'.$i);
                        $file_name = time()."-".$file->getClientOriginalExtension();
                        $file->move('files', $file_name);
                        DB::table('custom_field_item')->where('item_id', '=', $item->id)

resources/views/items/create.blade.php
@extends('layouts.main_admin')

@section('title', 'Items')

@section('content')

	<div class="container">
		<h5>{{ $title }}</h5>

		<form action="{{ route('items.store') }}" method="POST" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div class="col s12">
		      <ul class="tabs">
		      	@foreach($languages as $language)
		        	<li class="tab col s3">
		        		<a href="#{{ $language->slug }}">{{ $language->name }}</a>
		        	</li>
		        @endforeach
		      </ul>
		    </div>
			
			@foreach($languages as $language)
			<div class="col s12" id="{{ $language->slug }}">
				<div class="input-field" style="padding-top: 20px;">
					<input type="text" id="title_{{ $language->slug }}" name="title_{{ $language->slug }}" class="validate">
					<label for="title">Title</label>								
				</div>

				@if($language->slug == 'en')
				<input type="hidden" name="category_id" value="{{ $category_id }}" >

				<div class="input-field" style="padding-top: 20px;">
				    <select name="tags_{{ $language->slug }}[]" multiple="multiple">
				      <option value="" disabled selected>Choose your option</option>
				      @foreach($tags as $tag)
						<option value="{{ $tag->id }}">{{ $tag->name }}</option>
				      @endforeach
				      
				    </select>
				    <label for="tags">Tags</label>
				</div>

				

				<div class="file-field input-field"  style="padding-top: 20px;">
			      <div class="btn">
			        <span>Image</span>
			        <input type="file" type="text" name="image" >
			      </div>
			      <div class="file-path-wrapper">
			        <input class="file-path validate">
			      </div>
    			</div>
    			@endif

    			<div style="padding-top: 20px;">
					<label for="desc">Description</label>
					<textarea name="desc_{{ $language->slug }}" id="desc_{{ $language->slug }}"></textarea>
    			</div>
				
				<div style="padding-top: 20px;">
					<label for="info">Information</label>
					<textarea name="info_{{ $language->slug }}" id="info_{{ $language->slug }}"></textarea>
    			</div>

				<input type="hidden" name="length" value="{{ count($custom_fields) }}">
				
				@if($language->slug == "en")
    			@for($i =0; $i < count($custom_fields); $i++)
					@if($custom_fields[$i]->type == 'integer')
						<div class="input-field" style="padding-top: 20px;">
							<input type="hidden" name="field_id{{ $i }}" value="{{ $custom_fields[$i]->id }}" >
							<input type="text" id="custom_field_value{{ $i }}" name="custom_field_value{{ $i }}" class="validate">
							<label for="custom_field_value{{ $i }}">{{ $custom_fields[$i]->field_key }}</label>
						</div>
					@elseif($custom_fields[$i]->type == 'string')
						<div class="input-field" style="padding-top: 20px;">
							<input type="hidden" name="field_id{{ $i }}" value="{{ $custom_fields[$i]->id }}" >
							<input type="text" id="custom_field_value{{ $i }}" name="custom_field_value{{ $i }}" class="validate">
							<label for="custom_field_value{{ $i }}">{{ $custom_fields[$i]->field_key }}</label>
						</div>

		    		@elseif($custom_fields[$i]->type == 'file')
		    			<div class="file-field input-field"  style="padding-top: 20px;">
		    			<input type="hidden" name="field_id{{ $i }}" value="{{ $custom_fields[$i]->id }}" >
					      <div class="btn">
					        <span>{{ $custom_fields[$i]->field_key }}</span>
					        <input type="file" type="text" name="custom_field_value_file{{ $i }}" >
					      </div>
					      <div class="file-path-wrapper">
					        <input class="file-path validate">
					      </div>
		    			</div>
					@endif
    			@endfor
				@endif
				<div style="padding-top: 20px;">
					<button type="submit" class="btn waves-effect waves-light large">Submit</button>	
				</div>
			</div>
			@endforeach
		</form>
	</div>

@endsection

@section('script')
	<script type="text/javascript">
		$(document).ready(function() {
			$('select').material_select();
		});	
	</script>

	<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
    	
    		@foreach($languages as $l)
	        	CKEDITOR.replace('desc_{{ $l->slug }}');
	        	CKEDITOR.replace('info_{{ $l->slug }}');
        	@endforeach
    </script>

@endsection

resources/views/items/edit.blade.php
@extends('layouts.main_admin')

@section('title', 'Items')

@section('content')

	<div class="container">
		<h5>{{ $title }}</h5>

		<form action="{{ route('items.update', $item->id) }}" method="POST" enctype="multipart/form-data">
			{{ csrf_field() }}
			{{ method_field('PUT') }}
			<div class="col s12">
		      <ul class="tabs">
		      	@foreach($languages as $language)
		        	<li class="tab col s3">
		        		<a href="#{{ $language->slug }}">{{ $language->name }}</a>
		        	</li>
		        @endforeach
		      </ul>
		    </div>
			
			@foreach($languages as $language)
			<div class="col s12" id="{{ $language->slug }}">
				<div class="input-field" style="padding-top: 20px;">
					<input type="text" id="title_{{ $language->slug }}" name="title_{{ $language->slug }}" class="validate" value="{{ $item->languages->find($language->id)->pivot->title or old('title') }}">
					<label for="title">Title</label>
															
				</div>

				@if($language->slug == 'en')
				<input type="hidden" name="category_id" value="{{ $category_id }}" >
				<div class="input-field" style="padding-top: 20px;">
				    <select name="tags[]" multiple="multiple">
				      <option value="" disabled selected>Choose your option</option>
				      @foreach($tags as $tag)
						<option value="{{ $tag->id }}">{{ $tag->name }}</option>
				      @endforeach
				      
				    </select>
				    <label for="tags">Tags</label>
				</div>


				<div class="file-field input-field"  style="padding-top: 20px;">
			      <div class="btn">
			        <span>Image</span>
			        <input type="file" type="text" name="image" >
			      </div>
			      <div class="file-path-wrapper">
			        <input class="file-path validate" value="{{ $item->image or old('image') }}">
			        <img class="left" height="128" width="128" src="/images/{{ $item->image }}">
			      </div>
    			</div>
    			@endif

    			<div style="padding-top: 20px;">
					<label for="desc">Description</label>
					<textarea name="desc_{{ $language->slug }}" id="desc_{{ $language->slug }}">{{ $item->languages->find($language->id)->pivot->desc or old('desc') }}</textarea>
    			</div>
				
				<div style="padding-top: 20px;">
					<label for="info">Information</label>
					<textarea name="info_{{ $language->slug }}" id="info_{{ $language->slug }}">{{ $item->languages->find($language->id)->pivot->info or old('info') }}</textarea>
    			</div>

    			<input type="hidden" name="length" value="{{ count($custom_fields) }}">

				@if($language->slug == 'en')
    			@for($i =0; $i < count($custom_fields); $i++)
					@if($custom_fields[$i]->type == 'integer')
						<div class="input-field" style="padding-top: 20px;">
							<input type="hidden" name="field_id{{ $i }}" value="{{ $custom_fields[$i]->id }}" >
							<input type="text" id="custom_field_value{{ $i }}" name="custom_field_value{{ $i }}" class="validate" value="{{ $custom_fields[$i]->value }}">
							<label for="custom_field_value">{{ $custom_fields[$i]->field_key }}</label>
						</div>
					@elseif($custom_fields[$i]->type == 'string')
						<div class="input-field" style="padding-top: 20px;">
							<input type="hidden" name="field_id{{ $i }}" value="{{ $custom_fields[$i]->id }}" >
							<input type="text" id="custom_field_value{{ $i }}" name="custom_field_value{{ $i }}" class="validate" value="{{ $custom_fields[$i]->value }}">
							<label for="custom_field_value">{{ $custom_fields[$i]->field_key }}</label>
						</div>

		    		@elseif($custom_fields[$i]->type == 'file')
		    			<div class="file-field input-field"  style="padding-top: 20px;">
		    			<input type="hidden" name="field_id{{ $i }}" value="{{ $custom_fields[$i]->id }}" >
					      <div class="btn">
					        <span>{{ $custom_fields[$i]->field_key }}</span>
					        <input type="file" type="text" name="custom_field_value_file{{ $i }}" >
					      </div>
					      <div class="file-path-wrapper">
					        <input class="file-path validate">
					      </div>
		    			</div>
					@endif
    			@endfor
    			@endif
				
			</div>
			@endforeach
			<div style="padding-top: 20px;">
				<button type="submit" class="btn waves-effect waves-light large">Submit</button>	
			</div>
		</form>
	</div>

@endsection

@section('script')
	<script type="text/javascript">
		$(document).ready(function() {
			$('select').material_select();
		});	
	</script>

	<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
    	@foreach($languages as $language)
	        CKEDITOR.replace('desc_{{$language->slug}}');
    	    CKEDITOR.replace('info_{{$language->slug}}');
        @endforeach
    </script>

@endsection

resources/views/items/index.blade.php
@extends('layouts.main_admin')

@section('title', 'Items')


@section('content')
	<div class="row" style="padding-top: 50px;">
		<div class="col s12">
			<a class="waves-effect waves-light btn" href="{{ route('items.create') }}">Create New Item</a>
		<table class="bordered highlight">
			<thead>
				<tr>
					<th>#</th>
					<th>Title</th>
					<th>Category</th>
					<th></th>
					
				</tr>
			</thead>

			<tbody>
				
					@foreach($items as $item)
					<tr>
						<td>{{ $item->id }}</td>
						<td><a href="{{ route('items.show', $item->id) }}">{{ $item->title }}</a></td>
						<td>{{ App\Category::where('id', $item->category_id)->value('title') }}</td>
						<td class="right">
						<form action="{{ route('items.destroy', $item->id) }}" method="POST">
							<input type="hidden" name="_method" value="DELETE">
    						<input type="hidden" name="_token" value="{{ csrf_token() }}">
							<button class="waves-effect waves-light btn red tiny" type="submit">Delete</button>	
						</form>
						</td>
						
						
					</tr>
					@endforeach
				
			</tbody>
		</table>	
		</div>
			
	</div>
	
@endsection

resources/views/items/show.blade.php
@extends('layouts.main_admin')


@section('content')
	<div class="row">
		
		<div class="col s8">
			@foreach(App\Language::all() as $language)
			@if($item->languages->find($language->id))
			<ul class="collapsible" data-collapsible="accordion">
				<li>
					<div class="collapsible-header active"><strong>Title</strong></div>
					<div class="collapsible-body">{{ $item->languages->find($language->id)->pivot->title }}</div>
				</li>

				<li>
					<div class="collapsible-header"><strong>Image</strong></div>
					<div class="collapsible-body"><img height="256" width="256" src="/images/{{$item->image}}"></div>
				</li>

				<li>
					<div class="collapsible-header"><strong>Description</strong></div>
					<div class="collapsible-body">{!! $item->languages->find($language->id)->pivot->desc !!}</div>
				</li>

				<li>
					<div class="collapsible-header"><strong>Information</strong></div>
					<div class="collapsible-body">{!! $item->languages->find($language->id)->pivot->info !!}</div>
				</li>

				@foreach($custom_fields as $custom_field)
					<li>
						<div class="collapsible-header"><strong>{{ $custom_field->field_key }}</strong></div>
						<div class="collapsible-body">{{ $custom_field->value }}</div>	
					</li>
				@endforeach
			</ul>
			@endif
			@endforeach
		</div>
	
	<div class="col s4">
		<div class="card">
            <div class="card-content">

              <p><strong>Created At:</strong> <h6>{{$item->created_at }}</h6></p>
              <p><strong>Updated At:</strong> <h6>{{$item->updated_at }}</h6></p>
              <p><strong>Created By:</strong> <h6>{{$item->created_by }}</h6></p>
              <p><strong>Updated By:</strong> <h6>{{$item->created_by }}</h6></p>             

            </div>
            <div class="card-action">
              <div class="left"><a href="{{ route('items.edit', $item->id) }}" class="waves-effect waves-light btn large">&nbsp; Edit &nbsp;</a></div>
              <div class="right">
              	<form action="{{ route('items.destroy', $item->id) }}" method="POST">
					<input type="hidden" name="_method" value="DELETE">
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					<button class="waves-effect waves-light btn red" type="submit">Delete</button>	
				</form>
              </div>

              <div style="padding-top:50px;"><a style="padding:0 80px;" href="{{ route('categories.show', $item->category_id) }}" class="waves-effect waves-light btn blue">Show All Items</a></div>
              <div>
            </div>
          </div>
	
</div>
</div>
@endsection


@section('script')
	<script type="text/javascript">
		$(document).ready(function(){
    		$('.collapsible').collapsible();
  		});	
	</script>
@endsection