routes/web.php
<?php
use App\Language;
use Illuminate\Http\Request;
use App\Category;
use App\Item;
use App\Tag;
use App\Comment;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


foreach(Language::all() as $language) {
	Route::group(['prefix' => $language->slug ], function() use ($language){
		Route::get('/', function () use ($language){
		    session(['slug' => $language->slug ]);
		    session(['lang_id'=> $language->id]);
		    session(['dir' => $language->direction]);
		    //return session('lang_id');
		    return view('welcome');
		});

		Route::get('/search', [ 'uses' => 'TagController@search', 'as' => 'search']);
		Route::get('/search/{text}', 'TagController@search2');
		Route::get('/comments_save', [ 'uses' => 'CommentController@store', 'as' => 'comment_save']);
	});
}



Route::get('/backend', function() {
    return view('admin.index');
})->middleware('auth');

Route::resource('/backend/categories', 'CategoryController');

Route::get('/backend/categories/custom_fields/create_custom_field/{id}', [ 'as' => 'categories.create_custom_field' ,function($id) {
	if(!auth()->user()->canDo('add.extrafield')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	return view('custom_fields.create', compact('id'));
}]);

Route::post('/backend/categories/custom_fields', [ 'as' => 'categories.store_custom_field' ,function(Request $request) {
	//return $request;
	DB::table('category_custom_field')->insert([
		'category_id' => $request->input('category_id'),
		'field_key' => $request->input('field_key'),
		'type' => $request->input('type')
	]);

	return redirect()->route('categories.show', $request->input('category_id'));
}]);

Route::delete('/backend/categories/custom_fields/{category_id}/{id}', [ 'as' => 'categories.delete_custom_field' ,function($category_id, $id) {
	if(!auth()->user()->canDo('delete.extrafield')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	
	//$items = Item::where('category_id', $category_id)->get();
	//foreach($items as $item) {
		DB::table('custom_field_item')->where('field_id', '=', $id)->delete();
	//}
	DB::table('category_custom_field')->where('id', '=', $id)->delete();
	return redirect()->route('categories.show', $category_id);
}]);

//Item Extra Field


Route::resource('/backend/items', 'ItemController')->middleware('auth');
Route::resource('comments', 'CommentController');
Route::resource('tags', 'TagController')->middleware('auth');

Route::resource('languages', 'LanguageController')->middleware('auth');

Route::get('/languages/translate/{id}', [ 'as' => 'languages.translate' ,function($id) {
		return view('languages.translate', compact('id'));
	}]);

Route::post('/languages/translate_text', [ 'as' => 'languages.store_text' ,function(Request $request) {
		if(!auth()->user()->canDo('translate.text')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
		DB::table('dictionary')->insert([
			'text' => $request->input('text'),
			'translated_text' => $request->input('translated_text'),
			'language_id' => $request->input('language_id')
		]);

		return redirect()->route('languages.show', $request->input('language_id'));
	}]);

Route::delete('/delete_text/{language_id}/{id}', function($language_id, $id) {
	if(!auth()->user()->canDo('delete.text')) {
            return redirect()->route('languages.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }
	DB::table('dictionary')->where('id', '=', $id)->delete();

	return redirect()->route('languages.show', $language_id);
});

Route::get('/backend/items/create/{id}', function($id) {
	if(!auth()->user()->canDo('create.item')) {
            return redirect()->route('categories.index')->withErrors([
                'error' => 'You are not authorize !'
            ]);
        }

	$languages = Language::all();
    $title = "Create Item";
    $category_id = $id;
    $custom_fields = DB::table('category_custom_field')->where('category_id', $id)->get();
    $tags = Tag::all();

    return view('items.create', compact('languages', 'category_id', 'title', 'custom_fields', 'tags'));
});
Route::resource('/backend/menus', 'MenuController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/backend/users', 'UserController')->middleware('auth');
Route::resource('/backend/roles', 'RoleController')->middleware('auth');
Route::post('/backend/roles/addpermissions', [ 'as' => 'roles.addpermissions', 'uses' => 'RoleController@addPermissions'])->middleware('auth');

resources/views/admin/partials/header.blade.php
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link type="text/css" rel="stylesheet" href="{{ url('/') }}/css/materialize.min.css" media="screen,projection"/>
    
    
    <title>CMS</title>
    <script type="text/javascript" language="JavaScript">
		function showError(message) {
			alert('xxxxx');
			Materialize.toast(message, 4000, 'rounded');
		}	
	</script>
    
</head>

resources/views/admin/partials/messages.blade.php
@section('script')
	<script type="text/javascript">
		$(document).ready(function(){
			@if(count($errors))
				@foreach($errors->all() as $error)
	   				Materialize.toast('{{ $error }}', 4000, 'rounded')
	   			 @endforeach
   			 @endif

   			 @if(Session::has('success'))
   			 	Materialize.toast('{{ Session::get('success') }}', 4000, 'rounded')
   			 @endif
		});	
	</script>

@endsection

resources/views/admin/partials/nav.blade.php
<header>
    <nav class="purple darken-4">
        <div style="font-size: xx-large;">&nbsp; @yield('title')</div>
    </nav>
    <ul class="side-nav fixed">
        <li>
            <div class="user-view">
                <div class="background">
                    <img src="{{ url('/') }}/images/user-view-bg.jpg">
                </div>
                <a href="#!user"><img class="circle" src="{{ url('/') }}/images/admin.png"></a>
                <a href="#!name"><span class="white-text name">{{ auth()->user()->name }}</span></a>
                <a href="#!email"><span class="white-text email">{{ auth()->user()->email }}</span></a>
            </div>
        </li>

        <li>
            <a href="#" class="waves-effect waves-teal">Dashboard</a>
        </li>
        
        @if(auth()->user()->type == "admin")
        <li><a href="{{ route('users.index') }}" class="waves-effect waves-teal">Users</a></li>
        <li><a href="{{ route('roles.index') }}" class="waves-effect waves-teal">Roles</a></li>
        @endif
        <li><a href="{{ route('languages.index') }}" class="waves-effect waves-teal">Languages</a></li>
        
        <li class="bold"><a href="{{ route('menus.index') }}" class="waves-effect waves-teal">Menus</a></li>
        <li><a href="{{ route('comments.index') }}" class="waves-effect waves-teal">Comments</a></li>
        <li><a href="{{ route('tags.index') }}" class="waves-effect waves-teal">Tags</a></li>
        <li class="bold"><a href="{{ route('categories.index') }}" class="waves-effect waves-teal">Categories</a></li>
        
    </ul>

</header>

resources/views/admin/partials/scripts.blade.php
<script type="text/javascript" src="{{ url('/') }}/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{{ url('/') }}/js/materialize.min.js"></script>

resources/views/admin/partials/stylesheet.blade.php
<style type="text/css">
    header, main, footer {
        padding-left: 300px;
    }

</style>